'use client';
import Link from 'next/link';
import {FormEvent,useState} from 'react';
import {Locale} from '../../i18n';
type Mode='verify-email'|'reset-password'|'forgot-password'|'resend-verification';
const copy={
 en:{'verify-email':'Verify your email','reset-password':'Reset password','forgot-password':'Forgot password','resend-verification':'Resend verification',email:'Email',password:'New password',submit:'Continue',login:'Back to sign in',success:'Done. You can sign in now.',sent:'If your account is eligible, an email has been sent. Check your inbox.',error:'This request could not be completed. Please retry or request a new link.',missing:'Open the complete link from your email.',working:'Please wait…'},
 fr:{'verify-email':'Vérifier votre adresse','reset-password':'Réinitialiser le mot de passe','forgot-password':'Mot de passe oublié','resend-verification':'Renvoyer la vérification',email:'Adresse e-mail',password:'Nouveau mot de passe',submit:'Continuer',login:'Retour à la connexion',success:'Terminé. Vous pouvez vous connecter.',sent:'Si votre compte est éligible, un e-mail a été envoyé.',error:'Action impossible. Réessayez ou demandez un nouveau lien.',missing:'Ouvrez le lien complet reçu par e-mail.',working:'Veuillez patienter…'},
 ar:{'verify-email':'تأكيد البريد الإلكتروني','reset-password':'إعادة تعيين كلمة المرور','forgot-password':'نسيت كلمة المرور','resend-verification':'إعادة إرسال التأكيد',email:'البريد الإلكتروني',password:'كلمة المرور الجديدة',submit:'متابعة',login:'العودة لتسجيل الدخول',success:'تم بنجاح. يمكنك تسجيل الدخول الآن.',sent:'إذا كان الحساب مؤهلاً فقد تم إرسال رسالة إلى بريدك.',error:'تعذر إتمام الطلب. حاول مجدداً أو اطلب رابطاً جديداً.',missing:'افتح الرابط الكامل من بريدك الإلكتروني.',working:'يرجى الانتظار…'}
};
export function IdentityForm({locale,mode}:{locale:Locale;mode:Mode}){const t=copy[locale];const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[done,setDone]=useState(false);const requiresToken=mode==='verify-email'||mode==='reset-password';async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const token=new URLSearchParams(window.location.hash.slice(1)).get('token');if(requiresToken&&!token){setMessage(t.missing);return;}setBusy(true);try{const body=requiresToken?{token,...(mode==='reset-password'?{password:String(data.get('password'))}:{})}:{email:String(data.get('email'))};const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/${mode}`,{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify(body)});if(!response.ok)throw new Error('IDENTITY_REQUEST_FAILED');setMessage(requiresToken?t.success:t.sent);setDone(true);if(requiresToken)window.history.replaceState(null,'',window.location.pathname);}catch{setMessage(t.error);}finally{setBusy(false);}}return <section className="view-shell"><h1>{t[mode]}</h1><form className="platform-form" style={{maxWidth:480}} onSubmit={submit}>{!requiresToken&&<label>{t.email}<input type="email" name="email" required autoComplete="email"/></label>}{mode==='reset-password'&&<label>{t.password}<input type="password" name="password" required minLength={12} maxLength={72} autoComplete="new-password"/></label>}<button className="button" disabled={busy||done}>{busy?t.working:t.submit}</button><p role="status">{message}</p><Link href={`/${locale}/login`}>{t.login}</Link>{requiresToken&&<Link href={`/${locale}/${mode==='verify-email'?'resend-verification':'forgot-password'}`}>{t[mode==='verify-email'?'resend-verification':'forgot-password']}</Link>}</form></section>;}
