'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useAuth } from '../../components/auth-provider';
import { adminFetch } from '../../lib/admin-api';
type User = { id: string; email: string; displayName: string; role: string; status: string; emailVerifiedAt: string | null };
const roleLabels: Record<string, string> = { CUSTOMER: 'Client', SUPPORT: 'Support', CONTENT_MANAGER: 'Responsable contenu', TECHNICAL_ADMIN: 'Administrateur technique', SUPER_ADMIN: 'Super administrateur', FINANCE: 'Finance' };
const statusLabels: Record<string, string> = { PENDING: 'En attente', ACTIVE: 'Actif', SUSPENDED: 'Suspendu' };
export function UsersAdmin() {
  const { user } = useAuth(); const [items, setItems] = useState<User[]>([]); const [search, setSearch] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(''); const [loading, setLoading] = useState(true);
  async function load(query = '') { setLoading(true); try { const response = await adminFetch('/admin/users?search=' + encodeURIComponent(query)); if (!response.ok) throw new Error('Impossible de charger les utilisateurs.'); setItems(await response.json()); } finally { setLoading(false); } }
  useEffect(() => { if (user?.role === 'SUPER_ADMIN') void Promise.resolve().then(() => load()).catch((error) => setMessage(String(error))); }, [user?.role]);
  async function submit(event: FormEvent, item: User) { event.preventDefault(); setBusy(item.id); setMessage(''); try { const response = await adminFetch('/admin/users/' + item.id, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ role: item.role, status: item.status }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || 'Mise à jour impossible.'); await load(search); setMessage('Accès mis à jour. Les anciennes sessions de ce compte ont été révoquées.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Mise à jour impossible.'); } finally { setBusy(''); } }
  if (user?.role !== 'SUPER_ADMIN') return <section className="admin-empty"><h2>Accès réservé</h2><p>Seul un super administrateur peut modifier les rôles et les statuts.</p></section>;
  return <section className="users-workspace"><form className="view-search" onSubmit={(event) => { event.preventDefault(); void load(search).catch((error) => setMessage(String(error))); }}><input aria-label="Rechercher un utilisateur" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nom ou adresse e-mail"/><button className="button">Rechercher</button></form><p className="platform-status" role="status">{message}</p>{loading ? <p className="muted">Chargement…</p> : !items.length ? <div className="admin-empty"><h2>Aucun utilisateur trouvé</h2><p>Modifiez la recherche ou affichez toute la liste.</p></div> : <div className="user-card-list">{items.map((item) => <form className="user-access-card" onSubmit={(event) => void submit(event, item)} key={item.id}><div className="user-identity"><strong>{item.displayName}</strong><span>{item.email}</span>{item.id === user.id && <small>Votre compte · modification protégée</small>}</div><label>Rôle<select disabled={item.id === user.id} value={item.role} onChange={(event) => setItems((rows) => rows.map((row) => row.id === item.id ? { ...row, role: event.target.value } : row))}>{Object.entries(roleLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Statut<select disabled={item.id === user.id} value={item.status} onChange={(event) => setItems((rows) => rows.map((row) => row.id === item.id ? { ...row, status: event.target.value } : row))}>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><button className="button secondary" disabled={!!busy || item.id === user.id}>{busy === item.id ? 'Enregistrement…' : 'Enregistrer'}</button></form>)}</div>}</section>;
}
