import{BadRequestException,ForbiddenException,Injectable,NotFoundException}from'@nestjs/common';
import{PaymentEventType,Prisma}from'@prisma/client';import{createHmac,randomUUID,timingSafeEqual}from'node:crypto';
import{PrismaService}from'../prisma/prisma.service';import{AddCartItemDto,PaymentWebhookDto,RegisterDeviceDto}from'./commerce.dto';import{periodMonths,priceTotals}from'./commerce-pricing';
@Injectable()export class CommerceService{
 constructor(private readonly prisma:PrismaService){}
 async cart(userId:string){const cart=await this.prisma.cart.findFirst({where:{userId,active:true},include:{items:{include:{package:{include:{prices:true,channels:true}}}}}});return cart?{...cart,totals:cart.items.map(i=>{const price=i.package.prices.find(p=>p.period===i.period&&p.currency===cart.currency&&p.active);return price?priceTotals(price.amountMinor,cart.countryCode):null})}:{items:[]};}
 async add(userId:string,dto:AddCartItemDto){const countryCode=dto.countryCode.toUpperCase(),currency=dto.currency.toUpperCase(),pack=await this.prisma.package.findFirst({where:{id:dto.packageId,status:'PUBLISHED',OR:[{allowedCountries:{has:countryCode}},{allowedCountries:{has:'ALL'}}]},include:{prices:{where:{period:dto.period,currency,active:true}}}});if(!pack||pack.prices.length!==1)throw new BadRequestException('PACKAGE_NOT_AVAILABLE_OR_PRICED');let cart=await this.prisma.cart.findFirst({where:{userId,active:true}});if(cart&&(cart.countryCode!==countryCode||cart.currency!==currency))throw new BadRequestException('CART_COUNTRY_OR_CURRENCY_MISMATCH');cart??=await this.prisma.cart.create({data:{userId,countryCode,currency}});try{await this.prisma.cartItem.create({data:{cartId:cart.id,packageId:pack.id,period:dto.period}});}catch{throw new BadRequestException('DUPLICATE_CART_ITEM');}return this.cart(userId);}
 async remove(userId:string,itemId:string){const item=await this.prisma.cartItem.findFirst({where:{id:itemId,cart:{userId,active:true}}});if(!item)throw new NotFoundException('CART_ITEM_NOT_FOUND');await this.prisma.cartItem.delete({where:{id:itemId}});return this.cart(userId);}
 async checkout(userId:string){const cart=await this.prisma.cart.findFirst({where:{userId,active:true},include:{items:{include:{package:{include:{prices:true,channels:true}}}}}});if(!cart?.items.length)throw new BadRequestException('CART_EMPTY');const orders=[];for(const item of cart.items){const price=item.package.prices.find(p=>p.active&&p.currency===cart.currency&&p.period===item.period);if(!price)throw new BadRequestException('PRICE_CHANGED_OR_UNAVAILABLE');const totals=priceTotals(price.amountMinor,cart.countryCode);orders.push(await this.prisma.order.create({data:{number:`ORD-${Date.now()}-${randomUUID().slice(0,8)}`,userId,packageId:item.packageId,period:item.period,status:'PAYMENT_PENDING',productSnapshot:{id:item.package.id,slug:item.package.slug,names:item.package.names,maxDevices:item.package.maxDevices,maxConcurrentStreams:item.package.maxConcurrentStreams},contentSnapshot:{channelIds:item.package.channels.map(c=>c.channelId),scopes:['LIVE','VOD','SERIES']},countryCode:cart.countryCode,currency:cart.currency,...totals}}));}await this.prisma.cart.update({where:{id:cart.id},data:{active:false}});return{orders};}
 async simulate(userId:string,orderId:string,type:PaymentEventType){if(process.env.NODE_ENV==='production')throw new ForbiddenException('PAYMENT_SIMULATOR_DISABLED');const order=await this.prisma.order.findFirst({where:{id:orderId,userId}});if(!order)throw new NotFoundException('ORDER_NOT_FOUND');const body={externalId:`sim-${randomUUID()}`,orderId,type};return this.process(body);}
 signature(body:PaymentWebhookDto){return createHmac('sha256',process.env.PAYMENT_SIMULATOR_SECRET??'local-payment-simulator').update(JSON.stringify(body)).digest('hex');}
 verify(body:PaymentWebhookDto,signature:string){const expected=Buffer.from(this.signature(body)),actual=Buffer.from(signature??'');if(expected.length!==actual.length||!timingSafeEqual(expected,actual))throw new ForbiddenException('INVALID_WEBHOOK_SIGNATURE');return this.process(body);}
 async process(body:PaymentWebhookDto){const existing=await this.prisma.paymentEvent.findUnique({where:{externalId:body.externalId}});if(existing)return{duplicate:true,eventId:existing.id};return this.prisma.$transaction(async tx=>{const order=await tx.order.findUnique({where:{id:body.orderId},include:{package:{include:{channels:true}}}});if(!order)throw new NotFoundException('ORDER_NOT_FOUND');const event=await tx.paymentEvent.create({data:{externalId:body.externalId,orderId:order.id,type:body.type,payload:body as unknown as Prisma.InputJsonValue}});if(body.type==='SUCCEEDED'){const startsAt=new Date(),expiresAt=new Date(startsAt);expiresAt.setUTCMonth(expiresAt.getUTCMonth()+periodMonths[order.period]);await tx.order.update({where:{id:order.id},data:{status:'PAID',paidAt:startsAt}});const subscription=await tx.subscription.upsert({where:{orderId:order.id},create:{orderId:order.id,userId:order.userId,packageId:order.packageId,status:'ACTIVE',startsAt,expiresAt},update:{status:'ACTIVE',startsAt,expiresAt}});await tx.entitlement.deleteMany({where:{subscriptionId:subscription.id}});await tx.entitlement.createMany({data:[{subscriptionId:subscription.id,scope:'VOD'},{subscriptionId:subscription.id,scope:'SERIES'},...order.package.channels.map(c=>({subscriptionId:subscription.id,scope:'LIVE' as const,channelId:c.channelId}))]});}else if(body.type==='DELAYED')await tx.order.update({where:{id:order.id},data:{status:'PAYMENT_PENDING'}});else if(body.type==='FAILED')await tx.order.update({where:{id:order.id},data:{status:'FAILED'}});else{const status=body.type==='REFUNDED'?'REFUNDED':'DISPUTED';await tx.order.update({where:{id:order.id},data:{status}});const subscriptions=await tx.subscription.findMany({where:{orderId:order.id}});await tx.subscription.updateMany({where:{orderId:order.id},data:{status:'SUSPENDED'}});await tx.entitlement.updateMany({where:{subscriptionId:{in:subscriptions.map(s=>s.id)}},data:{active:false}});await tx.playbackSession.updateMany({where:{userId:order.userId,status:'ACTIVE'},data:{status:'ENDED',endedAt:new Date()}});}return{duplicate:false,eventId:event.id,type:body.type};});}
 async renew(userId:string,id:string){const sub=await this.prisma.subscription.findFirst({where:{id,userId},include:{package:{include:{prices:true,channels:true}},order:true}});if(!sub)throw new NotFoundException('SUBSCRIPTION_NOT_FOUND');const price=sub.package.prices.find(p=>p.active&&p.currency===sub.order.currency&&p.period===sub.order.period);if(!price)throw new BadRequestException('RENEWAL_PRICE_UNAVAILABLE');const totals=priceTotals(price.amountMinor,sub.order.countryCode);return this.prisma.order.create({data:{number:`REN-${Date.now()}-${randomUUID().slice(0,8)}`,userId,packageId:sub.packageId,period:sub.order.period,status:'PAYMENT_PENDING',productSnapshot:{id:sub.package.id,slug:sub.package.slug,names:sub.package.names,maxDevices:sub.package.maxDevices,maxConcurrentStreams:sub.package.maxConcurrentStreams},contentSnapshot:{channelIds:sub.package.channels.map(c=>c.channelId),scopes:['LIVE','VOD','SERIES']},countryCode:sub.order.countryCode,currency:sub.order.currency,...totals}});}
 async account(userId:string){await this.expire(userId);return this.prisma.user.findUniqueOrThrow({where:{id:userId},select:{id:true,email:true,displayName:true,subscriptions:{include:{package:{select:{id:true,slug:true,names:true,maxDevices:true,maxConcurrentStreams:true}},entitlements:true},orderBy:{createdAt:'desc'}},orders:{orderBy:{createdAt:'desc'}},devices:{orderBy:{lastSeenAt:'desc'}}}});}
 async registerDevice(userId:string,dto:RegisterDeviceDto){const active=await this.prisma.subscription.findFirst({where:{userId,status:'ACTIVE',expiresAt:{gt:new Date()}},include:{package:true}});if(!active)throw new ForbiddenException('ACTIVE_SUBSCRIPTION_REQUIRED');const count=await this.prisma.customerDevice.count({where:{userId}}),known=await this.prisma.customerDevice.findUnique({where:{userId_deviceId:{userId,deviceId:dto.deviceId}}});if(!known&&count>=active.package.maxDevices)throw new ForbiddenException('DEVICE_LIMIT_REACHED');return this.prisma.customerDevice.upsert({where:{userId_deviceId:{userId,deviceId:dto.deviceId}},create:{userId,...dto},update:{label:dto.label,lastSeenAt:new Date()}});}
 async entitlement(userId:string,targetType:'MEDIA'|'EPISODE'|'CHANNEL',targetId:string){await this.expire(userId);const scope=targetType==='CHANNEL'?'LIVE':targetType==='MEDIA'?'VOD':'SERIES';const allowed=await this.prisma.entitlement.count({where:{active:true,scope,channelId:scope==='LIVE'?targetId:null,subscription:{userId,status:'ACTIVE',expiresAt:{gt:new Date()}}}});if(!allowed)throw new ForbiddenException('SUBSCRIPTION_ENTITLEMENT_REQUIRED');const sub=await this.prisma.subscription.findFirstOrThrow({where:{userId,status:'ACTIVE',expiresAt:{gt:new Date()}},include:{package:true}});return sub.package;}
 private async expire(userId:string){const expired=await this.prisma.subscription.findMany({where:{userId,status:'ACTIVE',expiresAt:{lte:new Date()}},select:{id:true}});if(!expired.length)return;await this.prisma.subscription.updateMany({where:{id:{in:expired.map(v=>v.id)}},data:{status:'EXPIRED'}});await this.prisma.entitlement.updateMany({where:{subscriptionId:{in:expired.map(v=>v.id)}},data:{active:false}});await this.prisma.playbackSession.updateMany({where:{userId,status:'ACTIVE'},data:{status:'ENDED',endedAt:new Date()}});}
}
