import { Injectable } from '@nestjs/common';
import { SourceTestOutcome, SourceType } from '@prisma/client';
import { SourceCredentials } from './source-vault.service';
import { UrlPolicyService } from './url-policy.service';
import { PortalClient } from './portal-client';

type SourceConfig={type:SourceType;baseUrl:string;epgUrl:string|null;userAgent:string|null;allowedHosts:string[]};
export type ConnectorResult={outcome:SourceTestOutcome;latencyMs:number;capabilities?:Record<string,unknown>;errorCode?:string;detail?:string;expiresAt?:Date;maxConnections?:number};
@Injectable()
export class SourceConnectorsService {
 constructor(private readonly policy:UrlPolicyService){}
 async test(source:SourceConfig,secret:SourceCredentials):Promise<ConnectorResult>{const started=Date.now();try{if(source.type==='M3U'&&source.baseUrl.includes('uploaded-m3u.invalid'))return this.uploadedM3u(secret,started);await this.policy.validate(source.baseUrl,source.allowedHosts);if(source.epgUrl)await this.policy.validate(source.epgUrl,source.allowedHosts);switch(source.type){case'M3U':return await this.m3u(source,started);case'XTREAM':return await this.xtream(source,secret,started);case'DIRECT':return await this.direct(source,started);case'PORTAL_MAC':return await this.portal(source,secret,started);}}catch(error){const code=error instanceof Error?error.message:'SOURCE_TEST_FAILED';const outcome:SourceTestOutcome=error instanceof SyntaxError||code.includes('FORMAT')||code.includes('RESPONSE_INVALID')?'INVALID_FORMAT':code.includes('AUTH')||code.includes('HANDSHAKE_REJECTED')?'AUTH_FAILED':code.includes('BLOCKED')||code.includes('PRIVATE')||code.includes('ALLOWED')?'BLOCKED':'UNREACHABLE';return{outcome,latencyMs:Date.now()-started,errorCode:error instanceof SyntaxError?'SOURCE_RESPONSE_INVALID_JSON':code,detail:this.safe(code)};}}
 private uploadedM3u(secret:SourceCredentials,started:number):ConnectorResult{const content=secret.apiToken?.replace(/^\uFEFF/,'').trimStart();if(!content?.startsWith('#EXTM3U'))return this.result('INVALID_FORMAT',started,'M3U_HEADER_MISSING');if(!/^#EXTINF:/m.test(content))return this.result('INVALID_FORMAT',started,'M3U_NO_ENTRIES');return{outcome:'SUCCESS',latencyMs:Date.now()-started,capabilities:{live:true,movies:true,series:true,uploadedFile:true}};}
 private async request(url:URL,source:SourceConfig,init:RequestInit={}){for(let redirects=0;redirects<=3;redirects++){await this.policy.validate(url.toString(),source.allowedHosts);const response=await fetch(url,{...init,redirect:'manual',signal:AbortSignal.timeout(8000),headers:{'user-agent':source.userAgent??'Streamly-Source-Tester/1.0',accept:'application/json, application/x-mpegURL, application/vnd.apple.mpegurl, */*',...init.headers}});if(response.status>=300&&response.status<400){const location=response.headers.get('location');if(!location) return response;url=new URL(location,url);continue;}return response;}throw new Error('SOURCE_TOO_MANY_REDIRECTS');}
 private async m3u(source:SourceConfig,started:number):Promise<ConnectorResult>{const response=await this.request(new URL(source.baseUrl),source,{headers:{range:'bytes=0-4095'}});if(response.status===401||response.status===403)return this.result('AUTH_FAILED',started,'SOURCE_AUTH_FAILED');if(!response.ok)return this.httpError(response.status,started);const reader=response.body?.getReader();const chunk=await reader?.read();await reader?.cancel();const head=new TextDecoder().decode(chunk?.value).slice(0,4096).replace(/^\uFEFF/,'').trimStart();if(!head.startsWith('#EXTM3U'))return this.result('INVALID_FORMAT',started,'M3U_HEADER_MISSING');return{outcome:'SUCCESS',latencyMs:Date.now()-started,capabilities:{live:true,movies:true,series:true,epg:!!source.epgUrl,streamingParser:true}};}
 private async xtream(source:SourceConfig,secret:SourceCredentials,started:number):Promise<ConnectorResult>{if(!secret.username||!secret.password)return this.result('AUTH_FAILED',started,'XTREAM_CREDENTIALS_REQUIRED');const url=new URL('/player_api.php',source.baseUrl);url.searchParams.set('username',secret.username);url.searchParams.set('password',secret.password);const response=await this.request(url,source);if(response.status===401||response.status===403)return this.result('AUTH_FAILED',started,'SOURCE_AUTH_FAILED');if(!response.ok)return this.httpError(response.status,started);const text=await this.limitedText(response,256_000);const data=JSON.parse(text) as {user_info?:{auth?:number|string;status?:string;exp_date?:string;max_connections?:string|number};server_info?:unknown};const user=data.user_info;if(!user||String(user.auth)!=='1')return this.result('AUTH_FAILED',started,'XTREAM_AUTH_FAILED');if(user.status?.toLowerCase()==='expired'||user.exp_date&&Number(user.exp_date)*1000<=Date.now())return this.result('EXPIRED',started,'XTREAM_ACCOUNT_EXPIRED');const expiresAt=user.exp_date?new Date(Number(user.exp_date)*1000):undefined;const maxConnections=user.max_connections?Number(user.max_connections):undefined;return{outcome:'SUCCESS',latencyMs:Date.now()-started,expiresAt,maxConnections,capabilities:{live:true,movies:true,series:true,accountStatus:user.status??'Active'}};}
 private async direct(source:SourceConfig,started:number):Promise<ConnectorResult>{const response=await this.request(new URL(source.baseUrl),source,{headers:{range:'bytes=0-1023'}});if(response.status===401||response.status===403)return this.result('AUTH_FAILED',started,'SOURCE_AUTH_FAILED');if(!response.ok)return this.httpError(response.status,started);return{outcome:'SUCCESS',latencyMs:Date.now()-started,capabilities:{live:true,contentType:response.headers.get('content-type')}};}
 private async portal(source:SourceConfig,secret:SourceCredentials,started:number):Promise<ConnectorResult>{if(!secret.macAddress)return this.result('AUTH_FAILED',started,'PORTAL_MAC_REQUIRED');const session=await new PortalClient(this.policy).connect({...source,syncLive:true,syncMovies:true,syncSeries:true},secret);return{outcome:'SUCCESS',latencyMs:Date.now()-started,capabilities:{portalReachable:true,authenticated:true,endpoint:session.endpoint.pathname,live:true,movies:true,series:true,requiresFreshPlaybackResolution:true,adapterMode:'MINISTRA_STALKER'}};}
 private async limitedText(response:Response,max:number){const reader=response.body?.getReader();if(!reader)return'';let size=0;const chunks:Uint8Array[]=[];while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>max){await reader.cancel();throw new Error('SOURCE_RESPONSE_TOO_LARGE');}chunks.push(part.value);}const out=new Uint8Array(size);let at=0;for(const chunk of chunks){out.set(chunk,at);at+=chunk.length;}return new TextDecoder().decode(out);}
 private httpError(status:number,started:number){return this.result('UNREACHABLE',started,`SOURCE_HTTP_${status}`);}
 private result(outcome:SourceTestOutcome,started:number,errorCode:string):ConnectorResult{return{outcome,latencyMs:Date.now()-started,errorCode,detail:this.safe(errorCode)};}
 private safe(value:string){return value.replace(/https?:\/\/\S+/gi,'[REDACTED_URL]').slice(0,200);}
}
