CREATE TYPE "ImportStatus" AS ENUM ('QUEUED','CONNECTING','DOWNLOADING','PARSING','STAGING','PREVIEW','APPLYING','COMPLETED','PARTIAL','FAILED','CANCELLED');
CREATE TYPE "ImportedItemKind" AS ENUM ('LIVE','MOVIE','SERIES','EPISODE','GROUP','EPG');
CREATE TYPE "ImportChangeType" AS ENUM ('ADD','UPDATE','UNCHANGED','REMOVE','CONFLICT','EXCLUDED');
CREATE TABLE "ImportJob" ("id" TEXT NOT NULL,"sourceId" TEXT NOT NULL,"status" "ImportStatus" NOT NULL DEFAULT 'QUEUED',"progress" INTEGER NOT NULL DEFAULT 0,"scope" "ImportedItemKind"[],"totalItems" INTEGER NOT NULL DEFAULT 0,"addedItems" INTEGER NOT NULL DEFAULT 0,"updatedItems" INTEGER NOT NULL DEFAULT 0,"unchangedItems" INTEGER NOT NULL DEFAULT 0,"removedItems" INTEGER NOT NULL DEFAULT 0,"excludedItems" INTEGER NOT NULL DEFAULT 0,"conflictItems" INTEGER NOT NULL DEFAULT 0,"errorCode" TEXT,"errorDetail" TEXT,"cancelRequested" BOOLEAN NOT NULL DEFAULT false,"startedAt" TIMESTAMP(3),"finishedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ImportJob_pkey" PRIMARY KEY("id"));
CREATE TABLE "ImportStagedItem" ("id" TEXT NOT NULL,"jobId" TEXT NOT NULL,"kind" "ImportedItemKind" NOT NULL,"remoteId" TEXT NOT NULL,"fingerprint" TEXT NOT NULL,"groupName" TEXT,"displayName" TEXT NOT NULL,"normalized" JSONB NOT NULL,"raw" JSONB,"changeType" "ImportChangeType" NOT NULL,"selected" BOOLEAN NOT NULL DEFAULT true,"reason" TEXT,"streamCiphertext" TEXT,"streamIv" TEXT,"streamAuthTag" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ImportStagedItem_pkey" PRIMARY KEY("id"));
CREATE TABLE "SourceCatalogItem" ("id" TEXT NOT NULL,"sourceId" TEXT NOT NULL,"kind" "ImportedItemKind" NOT NULL,"remoteId" TEXT NOT NULL,"fingerprint" TEXT NOT NULL,"groupName" TEXT,"displayName" TEXT NOT NULL,"normalized" JSONB NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"lastSeenAt" TIMESTAMP(3) NOT NULL,"channelId" TEXT,"mediaTitleId" TEXT,"episodeId" TEXT,"streamCiphertext" TEXT,"streamIv" TEXT,"streamAuthTag" TEXT,CONSTRAINT "SourceCatalogItem_pkey" PRIMARY KEY("id"));
CREATE TABLE "SourceImportRule" ("id" TEXT NOT NULL,"sourceId" TEXT NOT NULL,"field" TEXT NOT NULL,"pattern" TEXT NOT NULL,"exclude" BOOLEAN NOT NULL DEFAULT true,"targetGenreId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SourceImportRule_pkey" PRIMARY KEY("id"));
CREATE INDEX "ImportJob_sourceId_createdAt_idx" ON "ImportJob"("sourceId","createdAt");CREATE INDEX "ImportJob_status_createdAt_idx" ON "ImportJob"("status","createdAt");CREATE UNIQUE INDEX "ImportStagedItem_jobId_kind_remoteId_key" ON "ImportStagedItem"("jobId","kind","remoteId");CREATE INDEX "ImportStagedItem_jobId_changeType_selected_idx" ON "ImportStagedItem"("jobId","changeType","selected");CREATE UNIQUE INDEX "SourceCatalogItem_sourceId_kind_remoteId_key" ON "SourceCatalogItem"("sourceId","kind","remoteId");CREATE INDEX "SourceCatalogItem_sourceId_kind_active_idx" ON "SourceCatalogItem"("sourceId","kind","active");CREATE INDEX "SourceCatalogItem_fingerprint_idx" ON "SourceCatalogItem"("fingerprint");CREATE INDEX "SourceImportRule_sourceId_idx" ON "SourceImportRule"("sourceId");
ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_sourceId_fkey" FOREIGN KEY("sourceId") REFERENCES "SourceAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE;ALTER TABLE "ImportStagedItem" ADD CONSTRAINT "ImportStagedItem_jobId_fkey" FOREIGN KEY("jobId") REFERENCES "ImportJob"("id") ON DELETE CASCADE ON UPDATE CASCADE;ALTER TABLE "SourceCatalogItem" ADD CONSTRAINT "SourceCatalogItem_sourceId_fkey" FOREIGN KEY("sourceId") REFERENCES "SourceAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE;ALTER TABLE "SourceCatalogItem" ADD CONSTRAINT "SourceCatalogItem_channelId_fkey" FOREIGN KEY("channelId") REFERENCES "Channel"("id") ON DELETE SET NULL ON UPDATE CASCADE;ALTER TABLE "SourceCatalogItem" ADD CONSTRAINT "SourceCatalogItem_mediaTitleId_fkey" FOREIGN KEY("mediaTitleId") REFERENCES "MediaTitle"("id") ON DELETE SET NULL ON UPDATE CASCADE;ALTER TABLE "SourceCatalogItem" ADD CONSTRAINT "SourceCatalogItem_episodeId_fkey" FOREIGN KEY("episodeId") REFERENCES "Episode"("id") ON DELETE SET NULL ON UPDATE CASCADE;ALTER TABLE "SourceImportRule" ADD CONSTRAINT "SourceImportRule_sourceId_fkey" FOREIGN KEY("sourceId") REFERENCES "SourceAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE;ALTER TABLE "SourceImportRule" ADD CONSTRAINT "SourceImportRule_targetGenreId_fkey" FOREIGN KEY("targetGenreId") REFERENCES "Genre"("id") ON DELETE SET NULL ON UPDATE CASCADE;
