import{BadRequestException,Injectable}from'@nestjs/common';import{PrismaService}from'../prisma/prisma.service';import{LibraryImportDto,PopularityDto,ProgressDto,TargetDto}from'./discovery.dto';import{normalizeQuery,rankText}from'./search-ranking';
@Injectable()export class DiscoveryService{constructor(private readonly prisma:PrismaService){}
 async search(userId:string,q:string,limit:number){const normalized=normalizeQuery(q);if(!normalized)throw new BadRequestException('SEARCH_QUERY_EMPTY');const tokens=normalized.split(' ').slice(0,6),now=new Date();const visibility={OR:[{status:'PUBLISHED' as const},{status:'SCHEDULED' as const,scheduledFor:{lte:now}}]};const[media,channels]=await this.prisma.$transaction([this.prisma.mediaTitle.findMany({where:{AND:[visibility,{OR:tokens.map(token=>({searchText:{contains:token,mode:'insensitive'}}))}]},include:{images:true,genres:{include:{genre:true}},credits:{include:{person:true}}},take:100}),this.prisma.channel.findMany({where:{AND:[visibility,{OR:tokens.map(token=>({searchText:{contains:token,mode:'insensitive'}}))}]},include:{category:true},take:100})]);await this.prisma.searchHistory.upsert({where:{userId_normalizedQuery:{userId,normalizedQuery:normalized}},create:{userId,query:q,normalizedQuery:normalized},update:{query:q,searchedAt:new Date()}});const values=[...media.map(v=>({kind:v.type,id:v.id,slug:v.slug,names:v.names,images:v.images,score:rankText(q,[v.searchText,...v.credits.map(c=>c.person.displayName),...v.genres.map(g=>JSON.stringify(g.genre.names))].join(' '))})),...channels.map(v=>({kind:'LIVE',id:v.id,slug:v.slug,names:v.names,logoUrl:v.logoUrl,score:rankText(q,`${v.searchText} ${JSON.stringify(v.category.names)}`)}))];return values.sort((a,b)=>b.score-a.score).slice(0,limit);}
 history(userId:string){return this.prisma.searchHistory.findMany({where:{userId},orderBy:{searchedAt:'desc'},take:20});}clearSearch(userId:string){return this.prisma.searchHistory.deleteMany({where:{userId}});}
 async addFavorite(userId:string,dto:TargetDto){this.target(dto,false);return this.prisma.favorite.upsert({where:dto.mediaTitleId?{userId_mediaTitleId:{userId,mediaTitleId:dto.mediaTitleId}}:{userId_channelId:{userId,channelId:dto.channelId!}},create:{userId,mediaTitleId:dto.mediaTitleId,channelId:dto.channelId},update:{}});}
 async removeFavorite(userId:string,dto:TargetDto){this.target(dto,false);return this.prisma.favorite.deleteMany({where:{userId,mediaTitleId:dto.mediaTitleId,channelId:dto.channelId}});}
 favorites(userId:string){return this.prisma.favorite.findMany({where:{userId},include:{mediaTitle:{include:{images:true,movie:true,series:true}},channel:{include:{category:true}}},orderBy:{createdAt:'desc'}});}
 async progress(userId:string,dto:ProgressDto){this.target(dto,true);const target=dto.episodeId?{userId_episodeId:{userId,episodeId:dto.episodeId}}:dto.mediaTitleId?{userId_mediaTitleId:{userId,mediaTitleId:dto.mediaTitleId}}:{userId_channelId:{userId,channelId:dto.channelId!}};const data={positionSec:dto.positionSec,durationSec:dto.durationSec,completed:dto.completed,lastDeviceId:dto.deviceId,lastWatchedAt:new Date()};return this.prisma.watchProgress.upsert({where:target,create:{userId,mediaTitleId:dto.mediaTitleId,episodeId:dto.episodeId,channelId:dto.channelId,...data},update:data});}
 continueWatching(userId:string){return this.prisma.watchProgress.findMany({where:{userId,completed:false,OR:[{durationSec:null},{positionSec:{gt:0}}]},include:{mediaTitle:{include:{images:true}},episode:{include:{images:true,season:{include:{series:{include:{mediaTitle:{include:{images:true}}}}}}}},channel:true},orderBy:{lastWatchedAt:'desc'},take:30});}
 historyList(userId:string){return this.prisma.watchProgress.findMany({where:{userId},include:{mediaTitle:{include:{images:true}},episode:{include:{season:{include:{series:{include:{mediaTitle:true}}}}}},channel:true},orderBy:{lastWatchedAt:'desc'},take:200});}clearHistory(userId:string,id?:string){return this.prisma.watchProgress.deleteMany({where:{userId,...(id?{id}:{})}});}
 async nextEpisode(userId:string,episodeId:string){const episode=await this.prisma.episode.findUnique({where:{id:episodeId},include:{season:true}});if(!episode)return null;return this.prisma.episode.findFirst({where:{OR:[{seasonId:episode.seasonId,episodeNumber:{gt:episode.episodeNumber}},{season:{seriesId:episode.season.seriesId,seasonNumber:{gt:episode.season.seasonNumber}}}]},include:{season:true,images:true},orderBy:[{season:{seasonNumber:'asc'}},{episodeNumber:'asc'}]});}
 async similar(mediaTitleId:string){const source=await this.prisma.mediaTitle.findUnique({where:{id:mediaTitleId},include:{genres:true}});if(!source)return[];return this.prisma.mediaTitle.findMany({where:{id:{not:mediaTitleId},status:'PUBLISHED',type:source.type,genres:{some:{genreId:{in:source.genres.map(v=>v.genreId)}}}},include:{images:true},take:12});}
 async popular(){const since=new Date();since.setDate(since.getDate()-7);const scores=await this.prisma.popularityDaily.groupBy({by:['mediaTitleId'],where:{day:{gte:since}},_sum:{score:true},orderBy:{_sum:{score:'desc'}},take:10});const map=new Map(scores.map((v,i)=>[v.mediaTitleId,i]));const items=await this.prisma.mediaTitle.findMany({where:{id:{in:[...map.keys()]},status:'PUBLISHED'},include:{images:true}});return items.sort((a,b)=>map.get(a.id)!-map.get(b.id)!);}
 async recordPopularity(userId:string,dto:PopularityDto){void userId;const day=new Date();day.setUTCHours(0,0,0,0);return this.prisma.popularityDaily.upsert({where:{mediaTitleId_day:{mediaTitleId:dto.mediaTitleId,day}},create:{mediaTitleId:dto.mediaTitleId,day,starts:1,completions:dto.completed?1:0,uniqueViewers:1,score:dto.completed?3:1},update:{starts:{increment:1},completions:{increment:dto.completed?1:0},score:{increment:dto.completed?3:1}}});}
 async exportLibrary(userId:string){const[favorites,progress]=await Promise.all([this.prisma.favorite.findMany({where:{userId},select:{mediaTitleId:true,channelId:true,createdAt:true}}),this.prisma.watchProgress.findMany({where:{userId},select:{mediaTitleId:true,episodeId:true,channelId:true,positionSec:true,durationSec:true,completed:true,lastWatchedAt:true}})]);return{format:'streamly-library',version:1,exportedAt:new Date().toISOString(),favorites,progress};}
 async importLibrary(userId:string,dto:LibraryImportDto){const value=dto.library as{format?:string;version?:number;favorites?:TargetDto[];progress?:ProgressDto[]};if(value.format!=='streamly-library'||value.version!==1)throw new BadRequestException('LIBRARY_FORMAT_INVALID');let favorites=0,progress=0;for(const item of(value.favorites??[]).slice(0,2000)){await this.addFavorite(userId,item);favorites++;}for(const item of(value.progress??[]).slice(0,5000)){await this.progress(userId,{...item,positionSec:item.positionSec??0,completed:item.completed??false});progress++;}return{favorites,progress};}
 private target(dto:TargetDto,episode:boolean){const count=Number(!!dto.mediaTitleId)+Number(!!dto.channelId)+Number(episode&&!!dto.episodeId);if(count!==1)throw new BadRequestException('EXACTLY_ONE_LIBRARY_TARGET_REQUIRED');}}
