import { Injectable } from '@nestjs/common';import { ImportedItemKind,SourceAccount } from '@prisma/client';import { PortalClient } from '../sources/portal-client';import { SourceCredentials } from '../sources/source-vault.service';import { UrlPolicyService } from '../sources/url-policy.service';import { normalize,NormalizedSourceItem,parseM3u,responseLines } from './m3u-parser';import { createHash } from 'node:crypto';
@Injectable()export class ImportReaderService{constructor(private readonly policy:UrlPolicyService){}
 async read(source:SourceAccount,secret:SourceCredentials,onProgress?:(received:number,total:number)=>void|Promise<void>):Promise<NormalizedSourceItem[]>{const output:NormalizedSourceItem[]=[];for await(const batch of this.batches(source,secret,undefined,onProgress))output.push(...batch);return output;}
 async *batches(source:SourceAccount,secret:SourceCredentials,scope?:ImportedItemKind[],onProgress?:(received:number,total:number)=>void|Promise<void>):AsyncGenerator<NormalizedSourceItem[]>{
  const allowed=(item:NormalizedSourceItem)=>!scope?.length||scope.includes(item.kind);
  if(source.type==='PORTAL_MAC'){for await(const batch of new PortalClient(this.policy).catalogueBatches(source,secret,onProgress)){const filtered=batch.filter(allowed);if(filtered.length)yield filtered;}return;}
  if(source.type==='M3U'){const lines=source.baseUrl.includes('uploaded-m3u.invalid')?this.textLines(secret.apiToken??''):responseLines(await this.fetch(source,new URL(source.baseUrl)),1_000_000_000);let batch:NormalizedSourceItem[]=[];let received=0;for await(const item of parseM3u(lines)){if(!allowed(item))continue;batch.push(item);received++;if(batch.length>=500){yield batch;batch=[];await onProgress?.(received,0);}}if(batch.length)yield batch;await onProgress?.(received,received);return;}
  if(source.type==='XTREAM'){let batch:NormalizedSourceItem[]=[];for(const item of await this.xtream(source,secret)){if(!allowed(item))continue;batch.push(item);if(batch.length>=500){yield batch;batch=[];}}if(batch.length)yield batch;return;}
  if(source.type==='DIRECT'){const item=this.direct(source);if(allowed(item))yield[item];return;}
  throw new Error('SOURCE_TYPE_UNSUPPORTED');
 }
 private async fetch(source:SourceAccount,url:URL){for(let i=0;i<4;i++){await this.policy.validate(url.toString(),source.allowedHosts);const response=await globalThis.fetch(url,{redirect:'manual',signal:AbortSignal.timeout(30_000),headers:{'user-agent':source.userAgent??'Streamly-Importer/1.0'}});if(response.status>=300&&response.status<400){const location=response.headers.get('location');if(!location)throw new Error('SOURCE_REDIRECT_INVALID');url=new URL(location,url);continue;}if(!response.ok)throw new Error(`SOURCE_HTTP_${response.status}`);return response;}throw new Error('SOURCE_TOO_MANY_REDIRECTS');}
 private async m3u(source:SourceAccount,secret:SourceCredentials){const lines=source.baseUrl.includes('uploaded-m3u.invalid')?this.textLines(secret.apiToken??''):responseLines(await this.fetch(source,new URL(source.baseUrl)));const values:NormalizedSourceItem[]=[];for await(const item of parseM3u(lines))values.push(item);return values;}
 private async *textLines(content:string):AsyncGenerator<string>{for(const line of content.split(/\r?\n/))yield line;}
 private async xtream(source:SourceAccount,secret:SourceCredentials){if(!secret.username||!secret.password)throw new Error('XTREAM_CREDENTIALS_REQUIRED');const output:NormalizedSourceItem[]=[];const actions:[string,'LIVE'|'MOVIE'|'SERIES'][]=[['get_live_streams','LIVE'],['get_vod_streams','MOVIE'],['get_series','SERIES']];for(const[action,kind]of actions){if(kind==='LIVE'&&!source.syncLive||kind==='MOVIE'&&!source.syncMovies||kind==='SERIES'&&!source.syncSeries)continue;const url=new URL('/player_api.php',source.baseUrl);url.searchParams.set('username',secret.username);url.searchParams.set('password',secret.password);url.searchParams.set('action',action);const response=await this.fetch(source,url);const data=await this.jsonArray(response);for(const raw of data){const id=String(raw.stream_id??raw.series_id??'');const name=String(raw.name??'Untitled');if(!id)continue;const category=String(raw.category_id??'Sans catégorie');const streamRef=kind==='SERIES'?`xtream:series:${id}`:`xtream:${kind.toLowerCase()}:${id}`;output.push({kind,remoteId:id,fingerprint:createHash('sha256').update(`${kind}|${normalize(name)}|${raw.year??''}`).digest('hex'),displayName:name,groupName:category,streamRef,logoUrl:String(raw.stream_icon??raw.cover??'')||undefined,raw:{year:raw.year,rating:raw.rating,containerExtension:raw.container_extension}});}}return output;}
 private direct(source:SourceAccount):NormalizedSourceItem{return{kind:'LIVE',remoteId:'direct',fingerprint:createHash('sha256').update(`LIVE|${source.id}`).digest('hex'),displayName:source.name,groupName:'Direct',streamRef:source.baseUrl};}
 private async jsonArray(response:Response){const text=await response.text();if(text.length>100_000_000)throw new Error('SOURCE_RESPONSE_TOO_LARGE');const value=JSON.parse(text) as unknown;if(!Array.isArray(value))throw new Error('SOURCE_RESPONSE_INVALID_JSON');return value as Record<string,unknown>[];}}
