export const locales = ['fr', 'en', 'ar'] as const;
export type Locale = (typeof locales)[number];
export const isLocale = (value: string): value is Locale => locales.includes(value as Locale);
export const direction = (locale: Locale) => locale === 'ar' ? 'rtl' : 'ltr';
const messages = {
  fr: { brand: 'Streamly', title: 'La télévision qui vous ressemble', subtitle: 'Choisissez vos chaînes ou un pack. Une expérience rapide et simple sur tous vos écrans.', start: 'Découvrir les offres', login: 'Se connecter', register: 'Créer un compte', name: 'Nom', email: 'E-mail', password: 'Mot de passe', language: 'Langue', create: 'Créer mon compte', submitLogin: 'Connexion', secure: 'Paiement sécurisé', adaptive: 'Qualité adaptative', multilingual: 'Plusieurs langues', channels:'Chaînes', packages:'Packs', search:'Rechercher', country:'Pays', add:'Ajouter', total:'Total', calculate:'Calculer le prix', empty:'Aucun résultat disponible' },
  en: { brand: 'Streamly', title: 'Television made for you', subtitle: 'Pick your channels or a package. A fast and simple experience on every screen.', start: 'Explore plans', login: 'Sign in', register: 'Create account', name: 'Name', email: 'Email', password: 'Password', language: 'Language', create: 'Create my account', submitLogin: 'Sign in', secure: 'Secure payments', adaptive: 'Adaptive quality', multilingual: 'Multiple languages', channels:'Channels', packages:'Packages', search:'Search', country:'Country', add:'Add', total:'Total', calculate:'Calculate price', empty:'No result available' },
  ar: { brand: 'ستريملي', title: 'تلفزيون يناسبك', subtitle: 'اختر قنواتك أو باقتك واستمتع بتجربة سريعة وبسيطة على جميع الشاشات.', start: 'اكتشف العروض', login: 'تسجيل الدخول', register: 'إنشاء حساب', name: 'الاسم', email: 'البريد الإلكتروني', password: 'كلمة المرور', language: 'اللغة', create: 'إنشاء حسابي', submitLogin: 'دخول', secure: 'دفع آمن', adaptive: 'جودة متكيفة', multilingual: 'لغات متعددة', channels:'القنوات', packages:'الباقات', search:'بحث', country:'البلد', add:'إضافة', total:'المجموع', calculate:'احسب السعر', empty:'لا توجد نتائج' },
} as const;
export const getMessages = (locale: Locale) => messages[locale];
