'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
type Kind='categories'|'channels'|'packages'; type Item={id:string;slug:string;status?:string;names?:Record<string,string>};
const templates:Record<Kind,object>={
 categories:{slug:'sport',names:{fr:'Sport',en:'Sports',ar:'رياضة'},sortOrder:10,active:true},
 channels:{slug:'demo-sport',names:{fr:'Démo Sport',en:'Sports Demo',ar:'عرض رياضي'},description:{fr:'Chaîne de démonstration',en:'Demo channel',ar:'قناة تجريبية'},languageCode:'fr',countryCode:'ALL',categoryId:'REMPLACER',sortOrder:10,webAvailable:true,featured:false,status:'DRAFT',prices:[{currency:'EUR',period:'MONTH_1',amountMinor:149}],rights:[{countryCode:'ALL',webAllowed:true,mobileAllowed:true,tvAllowed:true,validFrom:'2026-01-01T00:00:00.000Z',validUntil:'2099-01-01T00:00:00.000Z',approved:true,contractRef:'INTERNAL-DEMO'}]},
 packages:{slug:'essentiel',names:{fr:'Essentiel',en:'Essential',ar:'أساسي'},description:{fr:'Le meilleur pour commencer',en:'The best way to start',ar:'أفضل بداية'},status:'DRAFT',featured:true,sortOrder:10,maxDevices:1,maxConcurrentStreams:1,allowedCountries:['ALL'],channelIds:[],prices:[{currency:'EUR',period:'MONTH_1',amountMinor:699}]}
};
export function AdminCatalog(){const [kind,setKind]=useState<Kind>('categories');const [items,setItems]=useState<Item[]>([]);const [payload,setPayload]=useState(JSON.stringify(templates.categories,null,2));const [message,setMessage]=useState('');
 const token=()=>sessionStorage.getItem('accessToken')??''; const load=useCallback(async()=>{try{const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL}/admin/catalog/${kind}`,{headers:{authorization:`Bearer ${token()}`}});setItems(response.ok?await response.json():[]);}catch{setItems([]);}},[kind]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 async function submit(event:FormEvent){event.preventDefault();try{const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL}/admin/catalog/${kind}`,{method:'POST',headers:{authorization:`Bearer ${token()}`,'content-type':'application/json'},body:payload});const body=await response.json();setMessage(response.ok?'Enregistré':JSON.stringify(body.message));if(response.ok)void load();}catch{setMessage('API indisponible');}}
 async function archive(id:string){if(!confirm('Archiver cet élément ?'))return;await fetch(`${process.env.NEXT_PUBLIC_API_URL}/admin/catalog/${kind}/${id}`,{method:'DELETE',headers:{authorization:`Bearer ${token()}`}});void load();}
 return <><div className="toolbar">{(['categories','channels','packages'] as Kind[]).map(value=><button className={`button ${kind===value?'':'secondary'}`} key={value} onClick={()=>{setKind(value);setPayload(JSON.stringify(templates[value],null,2));}}>{value}</button>)}</div><section className="catalog-grid">{items.map(item=><article className="card" key={item.id}><h2>{item.names?.fr??item.slug}</h2><p className="muted">{item.status??'ACTIVE'} · {item.slug}</p><button className="button secondary" onClick={()=>archive(item.id)}>Archiver</button></article>)}</section><section className="card"><h2>Ajouter : {kind}</h2><form onSubmit={submit}><label>Configuration JSON<textarea rows={18} value={payload} onChange={e=>setPayload(e.target.value)}/></label><button className="button">Enregistrer</button><p aria-live="polite">{message}</p></form></section></>}
