'use client';
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Locale } from '../i18n';

type Title={id:string;slug:string;type:'MOVIE'|'SERIES';names:Record<string,string>;releaseYear?:number;rating?:string;series?:{seasons:{episodes:unknown[]}[]};genres:{genre:{slug:string;names:Record<string,string>}}[];images:{type:string;url:string}[];playbackVariants:{quality?:string}[]};
const api=process.env.NEXT_PUBLIC_API_URL;

export function MediaCatalogue({locale,type}:{locale:Locale;type:'MOVIE'|'SERIES'}) {
  const [items,setItems]=useState<Title[]>([]), [search,setSearch]=useState(''), [genre,setGenre]=useState(''), [year,setYear]=useState(''), [sort,setSort]=useState('recent'), [loading,setLoading]=useState(true), [failed,setFailed]=useState(false);
  useEffect(()=>{const timer=setTimeout(async()=>{setLoading(true);setFailed(false);try{const q=new URLSearchParams({type,search,sort,page:'1',pageSize:'60'});if(genre)q.set('genre',genre);if(year)q.set('year',year);const r=await fetch(`${api}/media/titles?${q}`);if(!r.ok)throw new Error();const body=await r.json();setItems(body.items??[]);}catch{setItems([]);setFailed(true);}finally{setLoading(false);}},250);return()=>clearTimeout(timer);},[type,search,genre,year,sort]);
  const genres=new Map(items.flatMap(v=>v.genres.map(g=>[g.genre.slug,g.genre.names[locale]??g.genre.names.fr])));
  const copy=type==='MOVIE'
    ? locale==='en'?{label:'Movies',empty:'No movies match your filters.',clear:'Clear filters'}:locale==='ar'?{label:'أفلام',empty:'لا توجد أفلام تطابق عوامل التصفية.',clear:'مسح عوامل التصفية'}:{label:'Films',empty:'Aucun film ne correspond à vos filtres.',clear:'Effacer les filtres'}
    : locale==='en'?{label:'Series',empty:'No series match your filters.',clear:'Clear filters'}:locale==='ar'?{label:'مسلسلات',empty:'لا توجد مسلسلات تطابق عوامل التصفية.',clear:'مسح عوامل التصفية'}:{label:'Séries',empty:'Aucune série ne correspond à vos filtres.',clear:'Effacer les filtres'};
  const clear=()=>{setSearch('');setGenre('');setYear('');setSort('recent')};
  return <>
    <section className="media-heading"><div><p className="eyebrow">STREAMLY</p><h1>{copy.label}</h1></div><div className="catalog-filters"><input aria-label="Recherche" type="search" placeholder={locale==='en'?'Search':locale==='ar'?'بحث':'Rechercher'} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Genre" value={genre} onChange={e=>setGenre(e.target.value)}><option value="">{locale==='en'?'All genres':locale==='ar'?'كل الأنواع':'Tous les genres'}</option>{[...genres].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><input aria-label="Année" type="number" placeholder={locale==='en'?'Year':locale==='ar'?'السنة':'Année'} min="1888" max="2200" value={year} onChange={e=>setYear(e.target.value)}/><select aria-label="Tri" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">{locale==='en'?'Recent':'Récent'}</option><option value="rating">{locale==='en'?'Rating':'Note'}</option><option value="year">{locale==='en'?'Year':'Année'}</option><option value="title">{locale==='en'?'Title':'Titre'}</option></select></div></section>
    {loading?<div className="poster-grid" aria-label="Loading">{Array.from({length:8},(_,i)=><div className="poster skeleton" key={i}/>)}</div>:items.length===0?<section className="empty-state"><span className="empty-icon" aria-hidden="true">{failed?'!':'+'}</span><h2>{failed?(locale==='en'?'Content could not be loaded.':'Le contenu n’a pas pu être chargé.'):copy.empty}</h2><p>{failed?(locale==='en'?'Check your connection and try again.':'Vérifiez votre connexion puis réessayez.'):(locale==='en'?'Try a broader search or reset the filters.':'Essayez une recherche plus large ou réinitialisez les filtres.')}</p><button className="button secondary" onClick={clear}>{failed?(locale==='en'?'Try again':'Réessayer'):copy.clear}</button></section>:<section className="poster-grid">{items.map(item=>{const title=item.names[locale]??item.names.fr,poster=item.images.find(v=>v.type==='POSTER')?.url,count=item.series?.seasons.reduce((n,s)=>n+s.episodes.length,0),quality=item.playbackVariants.map(v=>v.quality).filter(Boolean)[0];return <Link className="poster-card" href={`/${locale}/${item.type==='MOVIE'?'movies':'series'}/${item.slug}`} key={item.id}><div className="poster"><PosterArtwork url={poster} title={title} type={item.type}/><span className="media-badge">{quality??(item.type==='MOVIE'?'FILM':'SÉRIE')}</span></div><h2>{title}</h2><p className="muted">{[item.releaseYear,item.rating&&`★ ${item.rating}`,count!==undefined&&`${count} épisodes`].filter(Boolean).join(' · ')}</p></Link>})}</section>}
  </>;
}
function PosterArtwork({url,title,type}:{url?:string;title:string;type:'MOVIE'|'SERIES'}){const[failed,setFailed]=useState(false);if(url&&!failed)return <img src={url} alt="" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>;return <span className={`poster-fallback ${type.toLowerCase()}`}><i aria-hidden="true">{type==='MOVIE'?'▶':'S'}</i><strong>{title}</strong><small>STREAMLY</small></span>}
