'use client';
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Locale } from '../i18n';
type Episode={id:string;episodeNumber:number;names:Record<string,string>;synopsis?:Record<string,string>;images:{url:string}[]};
type Detail={id:string;type:string;names:Record<string,string>;synopsis?:Record<string,string>;releaseYear?:number;ageRating?:string;rating?:string;movie?:{durationSec:number};genres:{genre:{names:Record<string,string>}}[];images:{type:string;url:string}[];credits:{character?:string;person:{displayName:string}}[];series?:{seasons:{id:string;seasonNumber:number;episodes:Episode[]}[]};playbackVariants:{quality?:string}[]};
const api=process.env.NEXT_PUBLIC_API_URL;
export function MediaDetail({locale,slug}:{locale:Locale;slug:string}){
 const[item,setItem]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[season,setSeason]=useState(0);
 useEffect(()=>{void fetch(`${api}/media/titles/${slug}`).then(r=>r.ok?r.json():null).then(setItem).finally(()=>setLoading(false));},[slug]);
 if(loading)return <div className="detail-hero skeleton"/>;if(!item)return <section className="detail-body empty-state"><span className="empty-icon" aria-hidden="true">!</span><h2>{locale==='en'?'This title is unavailable.':'Ce contenu est indisponible.'}</h2><p>{locale==='en'?'It may have been removed or is not available in your region.':'Il a peut-être été retiré ou n’est pas disponible dans votre région.'}</p><Link className="button secondary" href={`/${locale}/movies`}>{locale==='en'?'Back to browse':'Retour au catalogue'}</Link></section>;
 const backdrop=item.images.find(v=>v.type==='BACKDROP')?.url,poster=item.images.find(v=>v.type==='POSTER')?.url,current=item.series?.seasons[season];
 return <><section className="detail-hero" style={backdrop?{backgroundImage:`linear-gradient(90deg,#071019 10%,#071019aa),url(${backdrop})`}:undefined}><div className="detail-copy">{poster&&<img className="detail-poster" src={poster} alt=""/>}<div><p className="eyebrow">{item.type}</p><h1>{item.names[locale]??item.names.fr}</h1><p className="meta">{[item.releaseYear,item.ageRating,item.rating&&`★ ${item.rating}`,item.movie&&`${Math.round(item.movie.durationSec/60)} min`,item.playbackVariants.map(v=>v.quality).filter(Boolean)[0]].filter(Boolean).join(' · ')}</p><p className="lead">{item.synopsis?.[locale]??item.synopsis?.fr}</p>{item.playbackVariants.length>0&&<Link className="button" href={`/${locale}/watch/media/${item.id}`}>▶ Lecture</Link>}</div></div></section><div className="detail-body">{item.genres.length>0&&<p>{item.genres.map(v=>v.genre.names[locale]??v.genre.names.fr).join(' · ')}</p>}{item.credits.length>0&&<section><h2>Casting</h2><p className="muted">{item.credits.map(v=>`${v.person.displayName}${v.character?` (${v.character})`:''}`).join(' · ')}</p></section>}{item.series&&<section><div className="season-tabs">{item.series.seasons.map((v,i)=><button className={`button ${season===i?'':'secondary'}`} onClick={()=>setSeason(i)} key={v.id}>Saison {v.seasonNumber}</button>)}</div><div className="episodes">{current?.episodes.map(v=><article className="episode-card" key={v.id}>{v.images[0]&&<img src={v.images[0].url} alt=""/>}<div><h3>{v.episodeNumber}. {v.names[locale]??v.names.fr}</h3><p className="muted">{v.synopsis?.[locale]??v.synopsis?.fr}</p><Link className="button secondary" href={`/${locale}/watch/episode/${v.id}`}>▶ Lire l’épisode</Link></div></article>)}</div></section>}</div></>;
}
