"use client";

import Hls from "hls.js";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { adminFetch } from "../lib/admin-api";

type Mode = "movie" | "series" | "live";
type Provider = { id:string; name:string; slug:string; category:"vod"|"live"|"sports"; movieTemplate?:string|null; tvTemplate?:string|null; streamUrl?:string|null; isActive:boolean; rank:number };
type Preview = { url:string; hls:boolean; label:string };
const copy = {
  movie:{ title:"Sources Films", description:"Construisez l’adresse de lecture depuis l’identifiant du film.", token:"{id}", placeholder:"https://example.com/movie/{id}", test:"ID du film", value:"550" },
  series:{ title:"Sources Séries", description:"Construisez l’adresse de chaque épisode avec l’ID, la saison et l’épisode.", token:"{id}, {s} et {e}", placeholder:"https://example.com/tv/{id}/{s}/{e}", test:"ID de la série", value:"1399" },
  live:{ title:"Templates Live", description:"Modèles d’URL ou flux directs utilisés pour la lecture et le secours.", token:"une URL HTTP(S), avec {id} si nécessaire", placeholder:"https://example.com/live/{id}.m3u8", test:"ID de chaîne", value:"channel-1" },
} satisfies Record<Mode,{title:string;description:string;token:string;placeholder:string;test:string;value:string}>;
const presets:Record<Mode,{name:string;slug:string;template:string}[]> = {
  movie:[{name:"VidLink",slug:"vidlink",template:"https://vidlink.pro/movie/{id}"},{name:"VidSrc",slug:"vidsrc",template:"https://vidsrc.me/embed/movie/{id}"},{name:"2Embed",slug:"twoembed",template:"https://www.2embed.cc/embed/{id}"}],
  series:[{name:"VidLink",slug:"vidlink",template:"https://vidlink.pro/tv/{id}/{s}/{e}"},{name:"VidSrc",slug:"vidsrc",template:"https://vidsrc.me/embed/tv/{id}/{s}/{e}"},{name:"2Embed",slug:"twoembed",template:"https://www.2embed.cc/embedtv/{id}&s={s}&e={e}"}], live:[],
};

function slugify(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)}
function templateFor(item:Provider,mode:Mode){return mode==="movie"?item.movieTemplate??"":mode==="series"?item.tvTemplate??"":item.streamUrl??""}
function resolved(template:string,id:string,season:string,episode:string){return template.replaceAll("{id}",encodeURIComponent(id)).replaceAll("{s}",encodeURIComponent(season)).replaceAll("{e}",encodeURIComponent(episode))}
function payload(item:Provider,patch:Partial<Provider>={}){return{name:item.name,slug:item.slug,category:item.category,movieTemplate:item.movieTemplate||undefined,tvTemplate:item.tvTemplate||undefined,streamUrl:item.streamUrl||undefined,isActive:item.isActive,rank:item.rank,...patch}}
function readableError(value:unknown){const message=Array.isArray(value)?value.join(", "):String(value??"Erreur inconnue");if(message.includes("Unique constraint"))return"Ce nom technique existe déjà.";if(message.includes("INVALID_ACCESS_TOKEN")||message.includes("AUTHENTICATION_REQUIRED"))return"Votre session a expiré. Reconnectez-vous.";if(message.includes("INSUFFICIENT_PERMISSION"))return"Votre compte ne peut pas gérer les sources.";return message}

export function ProviderManager({mode="movie",onChanged}:{mode?:Mode;onChanged?:()=>void|Promise<void>}){
  const config=copy[mode];
  const [all,setAll]=useState<Provider[]>([]),[editing,setEditing]=useState<Provider|null>(null),[open,setOpen]=useState(false),[name,setName]=useState(""),[template,setTemplate]=useState(""),[active,setActive]=useState(true),[testId,setTestId]=useState(config.value),[season,setSeason]=useState("1"),[episode,setEpisode]=useState("1"),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
  const load=useCallback(async()=>{try{const response=await adminFetch("/admin/providers"),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(readableError(body.message));setAll(body)}catch(error){setMessage(error instanceof Error?error.message:"API indisponible.")}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const items=useMemo(()=>all.filter(item=>Boolean(templateFor(item,mode))).sort((a,b)=>a.rank-b.rank||a.name.localeCompare(b.name)),[all,mode]);
  function begin(item?:Provider,preset?:{name:string;slug:string;template:string}){setEditing(item??null);setName(item?.name??preset?.name??"");setTemplate(item?templateFor(item,mode):preset?.template??"");setActive(item?.isActive??true);setMessage("");setPreview(null);setOpen(true)}
  function close(){setOpen(false);setEditing(null);setMessage("");setPreview(null)}
  function validate(value:string){try{const url=new URL(value);if(!["http:","https:"].includes(url.protocol))return"Utilisez une URL HTTP ou HTTPS."}catch{return"L’URL n’est pas valide."}if(mode==="movie"&&!value.includes("{id}"))return"Le template Film doit contenir {id}.";if(mode==="series"&&["{id}","{s}","{e}"].some(token=>!value.includes(token)))return"Le template Série doit contenir {id}, {s} et {e}.";return""}
  function previewTemplate(value=template,label=name||"Test de lecture"){const error=validate(value);if(error){setMessage(error);return}const url=resolved(value,testId||config.value,season||"1",episode||"1");setPreview({url,hls:/\.m3u8(?:$|[?#])/i.test(url),label});setMessage(`URL générée : ${url}`)}
  async function save(event:FormEvent){event.preventDefault();const error=validate(template);if(error){setMessage(error);return}setBusy("save");const sameSlug=all.find(item=>item.slug===slugify(name)),base=editing??sameSlug,rank=base?.rank??Math.max(0,...all.map(item=>item.rank))+1;const body={name,slug:base?.slug??slugify(name),category:mode==="live"?"live":"vod",movieTemplate:mode==="movie"?template:base?.movieTemplate||undefined,tvTemplate:mode==="series"?template:base?.tvTemplate||undefined,streamUrl:mode==="live"?template:base?.streamUrl||undefined,isActive:active,rank};try{const response=await adminFetch(base?`/admin/providers/${base.id}`:"/admin/providers",{method:base?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(readableError(result.message));await load();await onChanged?.();close()}catch(errorValue){setMessage(errorValue instanceof Error?errorValue.message:"Enregistrement impossible.")}finally{setBusy("")}}
  async function update(item:Provider,changes:Partial<Provider>,success:string){setBusy(item.id);setMessage("");try{const response=await adminFetch(`/admin/providers/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload(item,changes))}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(readableError(result.message));setMessage(success);await load();await onChanged?.()}catch(error){setMessage(error instanceof Error?error.message:"Mise à jour impossible.")}finally{setBusy("")}}
  async function move(item:Provider,direction:-1|1){const index=items.findIndex(value=>value.id===item.id),other=items[index+direction];if(!other)return;setBusy(item.id);try{const responses=await Promise.all([adminFetch(`/admin/providers/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload(item,{rank:other.rank}))}),adminFetch(`/admin/providers/${other.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload(other,{rank:item.rank}))})]);if(responses.some(response=>!response.ok))throw new Error("Le nouvel ordre n’a pas pu être enregistré.");await load();await onChanged?.()}catch(error){setMessage(error instanceof Error?error.message:"Classement impossible.")}finally{setBusy("")}}
  async function remove(item:Provider){if(!window.confirm(`Supprimer « ${item.name} » de cette section ?`))return;const changes=mode==="movie"?{movieTemplate:null}:mode==="series"?{tvTemplate:null}:{streamUrl:null},hasOtherUse=mode==="movie"?item.tvTemplate||item.streamUrl:mode==="series"?item.movieTemplate||item.streamUrl:item.movieTemplate||item.tvTemplate;setBusy(item.id);try{const response=hasOtherUse?await adminFetch(`/admin/providers/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload(item,changes))}):await adminFetch(`/admin/providers/${item.id}`,{method:"DELETE"});if(!response.ok){const result=await response.json().catch(()=>({}));throw new Error(readableError(result.message))}setMessage("Source supprimée de cette section.");await load();await onChanged?.()}catch(error){setMessage(error instanceof Error?error.message:"Suppression impossible.")}finally{setBusy("")}}
  return <section className="template-manager">
    <header className="source-context-heading"><div><p className="eyebrow">SOURCES DE LECTURE</p><h2>{config.title}</h2><p className="muted">{config.description}</p></div><button className="button" type="button" onClick={()=>begin()}>Ajouter une source</button></header>
    {presets[mode].length>0&&items.length===0&&<div className="source-presets"><span>Démarrage rapide</span>{presets[mode].map(preset=><button type="button" key={preset.slug} onClick={()=>begin(undefined,preset)}>+ {preset.name}</button>)}</div>}
    <div className="template-list">{items.length===0?<div className="card source-empty"><span>＋</span><h3>Aucune source {mode==="movie"?"Film":mode==="series"?"Série":"Live"}</h3><p>Ajoutez un template, testez son URL, puis activez-le.</p><button className="button" type="button" onClick={()=>begin()}>Ajouter la première source</button></div>:items.map((item,index)=><article className="card template-row" key={item.id}>
      <div className="template-rank"><strong>{index+1}</strong><div><button type="button" aria-label="Monter" disabled={index===0||!!busy} onClick={()=>void move(item,-1)}>↑</button><button type="button" aria-label="Descendre" disabled={index===items.length-1||!!busy} onClick={()=>void move(item,1)}>↓</button></div></div>
      <div className="template-main"><div><h3>{item.name}</h3><span className={item.isActive?"health-pill good":"health-pill"}>{item.isActive?"Active":"Désactivée"}</span></div><code>{templateFor(item,mode)}</code></div>
      <div className="template-actions"><button type="button" className="button secondary" onClick={()=>previewTemplate(templateFor(item,mode),item.name)}>Tester</button><button type="button" className="button secondary" onClick={()=>begin(item)}>Modifier</button><button type="button" className="switch-button" aria-pressed={item.isActive} disabled={!!busy} onClick={()=>void update(item,{isActive:!item.isActive},item.isActive?"Source désactivée.":"Source activée.")}><span/>{item.isActive?"Activée":"Désactivée"}</button><button type="button" className="icon-danger" aria-label="Supprimer" onClick={()=>void remove(item)}>×</button></div>
    </article>)}</div>
    {message&&<p className="source-feedback" role="status">{message}</p>}
    {preview&&<div className="source-preview card"><div><strong>{preview.label}</strong><button type="button" onClick={()=>setPreview(null)}>Fermer</button></div><div className="view-player provider-preview">{preview.hls?<HlsPreview src={preview.url}/>:<iframe src={preview.url} title={preview.label} allow="autoplay; fullscreen; picture-in-picture; encrypted-media" allowFullScreen referrerPolicy="origin" sandbox="allow-scripts allow-same-origin allow-forms allow-presentation"/>}</div></div>}
    {open&&<div className="source-drawer-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><aside className="source-drawer" role="dialog" aria-modal="true" aria-labelledby="source-drawer-title"><header><div><p className="eyebrow">{editing?"MODIFICATION":"NOUVELLE SOURCE"}</p><h2 id="source-drawer-title">{editing?editing.name:config.title}</h2></div><button type="button" aria-label="Fermer" onClick={close}>×</button></header><form onSubmit={save}><label>Nom affiché<input required minLength={2} value={name} placeholder="Ex. Serveur principal" onChange={event=>setName(event.target.value)}/></label><label>Template URL<input required type="url" value={template} placeholder={config.placeholder} onChange={event=>setTemplate(event.target.value)}/><small>Variables attendues : {config.token}</small></label><div className="test-inputs"><label>{config.test}<input value={testId} onChange={event=>setTestId(event.target.value)}/></label>{mode==="series"&&<><label>Saison<input min={0} type="number" value={season} onChange={event=>setSeason(event.target.value)}/></label><label>Épisode<input min={0} type="number" value={episode} onChange={event=>setEpisode(event.target.value)}/></label></>}</div><button type="button" className="button secondary" onClick={()=>previewTemplate()}>Vérifier et prévisualiser</button><label className="checkbox"><input type="checkbox" checked={active} onChange={event=>setActive(event.target.checked)}/>Activer immédiatement</label>{message&&<p className="source-feedback" role="status">{message}</p>}<footer><button type="button" className="button secondary" onClick={close}>Annuler</button><button className="button" disabled={!!busy}>{busy==="save"?"Enregistrement…":"Enregistrer"}</button></footer></form></aside></div>}
  </section>
}

function HlsPreview({src}:{src:string}){const video=useRef<HTMLVideoElement>(null);useEffect(()=>{const element=video.current;if(!element)return;let hls:Hls|undefined;if(element.canPlayType("application/vnd.apple.mpegurl"))element.src=src;else if(Hls.isSupported()){hls=new Hls();hls.loadSource(src);hls.attachMedia(element)}return()=>{hls?.destroy();element.removeAttribute("src");element.load()}},[src]);return <video ref={video} controls playsInline preload="metadata"/>}
