'use client';
import { useEffect, useRef, useState } from 'react';
const api=process.env.NEXT_PUBLIC_API_URL;
type TargetType='MEDIA'|'EPISODE'|'CHANNEL';

export function SecurePlayer({targetType,targetId}:{targetType:TargetType;targetId:string}){
 const video=useRef<HTMLVideoElement>(null),[status,setStatus]=useState('Préparation…');
 useEffect(()=>{let cleanup:(()=>void|Promise<void>)|undefined,timer:ReturnType<typeof setInterval>|undefined,sessionId:string|undefined,cancelled=false;const authorization=`Bearer ${sessionStorage.getItem('accessToken')??''}`,deviceId=localStorage.getItem('streamlyDeviceId')??crypto.randomUUID();localStorage.setItem('streamlyDeviceId',deviceId);
  void(async()=>{try{const response=await fetch(`${api}/playback/sessions`,{method:'POST',headers:{authorization,'content-type':'application/json'},body:JSON.stringify({targetType,targetId,deviceId})});if(!response.ok){if(!cancelled)setStatus(response.status===401?'Connexion requise':'Lecture indisponible');return}const value=await response.json() as{sessionId:string;manifestUrl:string;streamType?:'mpegts'|'manifest'};sessionId=value.sessionId;if(cancelled||!video.current)return;const url=new URL(value.manifestUrl,new URL(api!).origin).toString();if(value.streamType==='mpegts'){const mpegts=await import('mpegts.js');if(!mpegts.default.isSupported()){setStatus('MPEG-TS non compatible avec ce navigateur.');return}const created=mpegts.default.createPlayer({type:'mpegts',isLive:true,url},{enableWorker:true,enableStashBuffer:false,liveBufferLatencyChasing:true}),onError=()=>{if(!cancelled){setStatus('Le flux du portail est temporairement indisponible.');void qoe(value.sessionId,'error',authorization)}};created.on(mpegts.default.Events.ERROR,onError);cleanup=()=>{created.off(mpegts.default.Events.ERROR,onError);created.pause();created.unload();created.detachMediaElement();created.destroy()};created.attachMediaElement(video.current);created.load();await created.play();}else{const shaka=await import('shaka-player'),created=new shaka.default.Player();cleanup=()=>created.destroy();await created.attach(video.current);created.configure({streaming:{bufferingGoal:20,rebufferingGoal:3,bufferBehind:30,retryParameters:{maxAttempts:3,baseDelay:500,backoffFactor:2,fuzzFactor:.2,timeout:10000}}});created.addEventListener('buffering',()=>void qoe(value.sessionId,'buffering',authorization));created.addEventListener('error',()=>{if(!cancelled)setStatus('Reconnexion…');void qoe(value.sessionId,'error',authorization)});await created.load(url);await video.current.play();}if(!cancelled)setStatus('');timer=setInterval(()=>{void fetch(`${api}/playback/sessions/${value.sessionId}/heartbeat`,{method:'POST',headers:{authorization}}).catch(()=>undefined)},30000);}catch{if(!cancelled)setStatus('Le flux est temporairement indisponible.');}})();
  return()=>{cancelled=true;if(timer)clearInterval(timer);if(sessionId)void fetch(`${api}/playback/sessions/${sessionId}/end`,{method:'POST',headers:{authorization,'content-type':'application/json'},body:'{}'}).catch(()=>undefined);void cleanup?.()};
 },[targetId,targetType]);
 return <div className="player-shell"><video ref={video} controls playsInline/><p aria-live="polite">{status}</p></div>;
}
async function qoe(id:string,type:string,authorization:string){try{await fetch(`${api}/playback/sessions/${id}/qoe`,{method:'POST',headers:{authorization,'content-type':'application/json'},body:JSON.stringify({type})})}catch{/* Playback continues when telemetry is unavailable. */}}
