import{BadRequestException,Injectable,NotFoundException}from'@nestjs/common';import{PrismaService}from'../prisma/prisma.service';import{UrlPolicyService}from'../sources/url-policy.service';import{parseXmltv}from'./xmltv';
@Injectable()export class EpgService{constructor(private readonly prisma:PrismaService,private readonly policy:UrlPolicyService){}
 async import(sourceId:string,urlOverride?:string){const source=await this.prisma.sourceAccount.findUnique({where:{id:sourceId}});if(!source)throw new NotFoundException('SOURCE_NOT_FOUND');const raw=urlOverride??source.epgUrl;if(!raw||!source.syncEpg)throw new BadRequestException('EPG_NOT_CONFIGURED');const run=await this.prisma.epgImportRun.create({data:{sourceId,status:'RUNNING'}});try{const url=new URL(raw);await this.policy.validate(url.toString(),source.allowedHosts);const response=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(30_000),headers:{'user-agent':source.userAgent??'Streamly-EPG/1.0'}});if(!response.ok)throw new Error(`EPG_HTTP_${response.status}`);const xml=await response.text();if(xml.length>100_000_000)throw new Error('EPG_TOO_LARGE');const parsed=parseXmltv(xml),allChannels=await this.prisma.channel.findMany({where:{status:{not:'ARCHIVED'}},select:{id:true,names:true,searchText:true}});const mappings=new Map<string,{id:string;channelId:string|null}>();for(const external of parsed.channels){const key=normalize(external.name),match=allChannels.find(c=>normalize(c.searchText).includes(key)||Object.values(c.names as Record<string,string>).some(n=>normalize(n)===key));const mapping=await this.prisma.epgChannelMapping.upsert({where:{sourceId_externalChannelId:{sourceId,externalChannelId:external.id}},create:{sourceId,externalChannelId:external.id,externalName:external.name,channelId:match?.id,confidence:match?1:null},update:{externalName:external.name,...(match?{channelId:match.id,confidence:1}:{})}});mappings.set(external.id,mapping);}let imported=0;for(const p of parsed.programs){let mapping=mappings.get(p.channelId);if(!mapping){const created=await this.prisma.epgChannelMapping.upsert({where:{sourceId_externalChannelId:{sourceId,externalChannelId:p.channelId}},create:{sourceId,externalChannelId:p.channelId},update:{}});mapping=created;mappings.set(p.channelId,created);}await this.prisma.epgProgram.upsert({where:{mappingId_externalId:{mappingId:mapping.id,externalId:p.id}},create:{mappingId:mapping.id,channelId:mapping.channelId,externalId:p.id,title:p.title,description:p.description,category:p.category,startAt:p.startAt,endAt:p.endAt},update:{channelId:mapping.channelId,title:p.title,description:p.description,category:p.category,startAt:p.startAt,endAt:p.endAt,sourceUpdatedAt:new Date()}});imported++;}await this.prisma.epgProgram.deleteMany({where:{mapping:{sourceId},endAt:{lt:new Date(Date.now()-48*3600_000)}}});return this.prisma.epgImportRun.update({where:{id:run.id},data:{status:'COMPLETED',channelsSeen:parsed.channels.length,programsImported:imported,invalidDates:parsed.invalidDates.length,finishedAt:new Date()}});}catch(e){await this.prisma.epgImportRun.update({where:{id:run.id},data:{status:'FAILED',errorCode:e instanceof Error?e.message:'EPG_IMPORT_FAILED',finishedAt:new Date()}});throw e;}}
 mappings(sourceId:string){return this.prisma.epgChannelMapping.findMany({where:{sourceId},include:{channel:{select:{id:true,slug:true,names:true}}},orderBy:[{channelId:'asc'},{externalName:'asc'}]});}
 async map(sourceId:string,externalId:string,channelId:string){const channel=await this.prisma.channel.findUnique({where:{id:channelId}});if(!channel)throw new NotFoundException('CHANNEL_NOT_FOUND');const mapping=await this.prisma.epgChannelMapping.update({where:{sourceId_externalChannelId:{sourceId,externalChannelId:externalId}},data:{channelId,confidence:1}});await this.prisma.epgProgram.updateMany({where:{mappingId:mapping.id},data:{channelId}});return mapping;}
 async guide(channelId?:string){const now=new Date(),from=new Date(now.getTime()-2*3600_000),to=new Date(now.getTime()+24*3600_000);const programs=await this.prisma.epgProgram.findMany({where:{channelId:channelId??{not:null},endAt:{gt:from},startAt:{lt:to}},include:{channel:{select:{id:true,slug:true,names:true,logoUrl:true,languageCode:true,countryCode:true,category:true}}},orderBy:[{channelId:'asc'},{startAt:'asc'}]});const latest=programs.reduce((v,p)=>p.endAt>v?p.endAt:v,new Date(0));return{generatedAt:now,stale:latest<now,programs};}
 async reminder(userId:string,programId:string){const program=await this.prisma.epgProgram.findUnique({where:{id:programId}});if(!program||program.startAt<=new Date())throw new BadRequestException('PROGRAM_NOT_REMINDABLE');const notifyAt=new Date(Math.max(Date.now(),program.startAt.getTime()-5*60_000));return this.prisma.programReminder.upsert({where:{userId_programId:{userId,programId}},create:{userId,programId,notifyAt},update:{notifyAt,sentAt:null}});}
 reminders(userId:string){return this.prisma.programReminder.findMany({where:{userId,program:{endAt:{gt:new Date()}}},include:{program:{include:{channel:true}}},orderBy:{notifyAt:'asc'}});}
 availability(){return this.prisma.channel.findMany({where:{status:'PUBLISHED'},select:{id:true,slug:true,names:true,playbackVariants:{where:{enabled:true},select:{id:true,reference:true,health:true}}}});}
}
function normalize(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
