import{BadRequestException,Injectable,NotFoundException}from'@nestjs/common';import{Prisma,PublicationStatus}from'@prisma/client';import{PrismaService}from'../prisma/prisma.service';import{BulkWorkflowDto,CollectionDto,HomeLayoutDto,StudioQueryDto}from'./editorial.dto';
@Injectable()export class EditorialService{constructor(private readonly prisma:PrismaService){}
 async studio(query:StudioQueryDto){const search=query.search?{contains:query.search,mode:'insensitive' as const}:undefined;const[media,channels,collections,layouts,genres,people]=await this.prisma.$transaction([this.prisma.mediaTitle.findMany({where:{...(query.status?{status:query.status}:{}),...(query.type?{type:query.type as 'MOVIE'|'SERIES'}:{}),...(search?{searchText:search}:{})},include:{movie:true,series:{include:{seasons:{include:{episodes:true}}}},images:true,genres:{include:{genre:true}},playbackVariants:true},orderBy:{updatedAt:'desc'},take:500}),this.prisma.channel.findMany({where:{...(query.status?{status:query.status}:{}),...(search?{searchText:search}:{})},include:{category:true,playbackVariants:true},orderBy:{updatedAt:'desc'},take:500}),this.prisma.editorialCollection.findMany({include:{items:{orderBy:{sortOrder:'asc'},include:{mediaTitle:{select:{id:true,names:true,type:true}},channel:{select:{id:true,names:true}}}}},orderBy:{sortOrder:'asc'}}),this.prisma.homeLayout.findMany({include:{rails:{include:{collection:true,items:{include:{mediaTitle:{select:{id:true,names:true}},channel:{select:{id:true,names:true}}}}},orderBy:{sortOrder:'asc'}}},orderBy:[{locale:'asc'},{countryCode:'asc'}]}),this.prisma.genre.findMany({where:{active:true},orderBy:{sortOrder:'asc'}}),this.prisma.person.findMany({orderBy:{sortName:'asc'},take:1000})]);return{media,channels,collections,layouts,genres,people};}
 async createCollection(dto:CollectionDto,actorId:string){this.validateTranslations(dto.names);this.targets(dto.items);this.schedule(dto.status,dto.scheduledFor);const value=await this.prisma.editorialCollection.create({data:this.collectionData(dto),include:{items:true}});await this.audit(actorId,'COLLECTION',value.id,'CREATE',null,value);return value;}
 async updateCollection(id:string,dto:CollectionDto,actorId:string){const before=await this.prisma.editorialCollection.findUnique({where:{id},include:{items:true}});if(!before)throw new NotFoundException('COLLECTION_NOT_FOUND');this.validateTranslations(dto.names);this.targets(dto.items);this.schedule(dto.status,dto.scheduledFor);const value=await this.prisma.editorialCollection.update({where:{id},data:{...this.collectionData(dto),items:{deleteMany:{},create:dto.items}},include:{items:true}});await this.audit(actorId,'COLLECTION',id,'UPDATE',before,value);return value;}
 async saveLayout(dto:HomeLayoutDto,actorId:string){this.schedule(dto.status,dto.scheduledFor);for(const rail of dto.rails){this.validateTranslations(rail.names);this.targets(rail.items);if(rail.type==='COLLECTION'&&!rail.collectionId)throw new BadRequestException('COLLECTION_RAIL_REQUIRES_COLLECTION');}const before=await this.prisma.homeLayout.findUnique({where:{locale_countryCode:{locale:dto.locale,countryCode:dto.countryCode}},include:{rails:{include:{items:true}}}});const data={status:dto.status,scheduledFor:dto.scheduledFor?new Date(dto.scheduledFor):null,publishedAt:dto.status==='PUBLISHED'?new Date():undefined,archivedAt:dto.status==='ARCHIVED'?new Date():null,rails:{create:dto.rails.map(rail=>({type:rail.type,names:this.json(rail.names)!,collectionId:rail.collectionId,sortOrder:rail.sortOrder,enabled:rail.enabled,rules:this.json(rail.rules),items:{create:rail.items}}))}};let value;if(before){await this.prisma.homeRail.deleteMany({where:{layoutId:before.id}});value=await this.prisma.homeLayout.update({where:{id:before.id},data,include:{rails:{include:{items:true}}}});}else value=await this.prisma.homeLayout.create({data:{locale:dto.locale,countryCode:dto.countryCode,...data},include:{rails:{include:{items:true}}}});await this.audit(actorId,'HOME_LAYOUT',value.id,before?'UPDATE':'CREATE',before,value);return value;}
 async publicHome(locale:string,countryCode:string){const now=new Date();return this.prisma.homeLayout.findFirst({where:{locale,countryCode:{in:[countryCode,'ALL']},OR:[{status:'PUBLISHED'},{status:'SCHEDULED',scheduledFor:{lte:now}}]},include:{rails:{where:{enabled:true},orderBy:{sortOrder:'asc'},include:{collection:{include:{items:{orderBy:{sortOrder:'asc'},include:{mediaTitle:{include:{images:true,movie:true}},channel:true}}}},items:{orderBy:{sortOrder:'asc'},include:{mediaTitle:{include:{images:true,movie:true}},channel:true}}}}}});}
 async workflow(dto:BulkWorkflowDto,actorId:string){if(!['MEDIA','CHANNEL','COLLECTION'].includes(dto.entityType))throw new BadRequestException('ENTITY_TYPE_INVALID');this.schedule(dto.status,dto.scheduledFor);const data={status:dto.status,scheduledFor:dto.status==='SCHEDULED'?new Date(dto.scheduledFor!):null,publishedAt:dto.status==='PUBLISHED'?new Date():undefined,archivedAt:dto.status==='ARCHIVED'?new Date():dto.status==='DRAFT'?null:undefined};let count=0;if(dto.entityType==='MEDIA')count=(await this.prisma.mediaTitle.updateMany({where:{id:{in:dto.ids}},data})).count;if(dto.entityType==='CHANNEL')count=(await this.prisma.channel.updateMany({where:{id:{in:dto.ids}},data})).count;if(dto.entityType==='COLLECTION')count=(await this.prisma.editorialCollection.updateMany({where:{id:{in:dto.ids}},data})).count;for(const id of dto.ids)await this.audit(actorId,dto.entityType,id,`BULK_${dto.status}`,null,{status:dto.status});return{count};}
 audits(entityType?:string,entityId?:string){return this.prisma.contentAuditEvent.findMany({where:{entityType,entityId},include:{actor:{select:{id:true,displayName:true}}},orderBy:{createdAt:'desc'},take:200});}
 private collectionData(dto:CollectionDto):Prisma.EditorialCollectionCreateInput{return{slug:dto.slug,names:this.json(dto.names)!,description:this.json(dto.description),type:dto.type,rules:this.json(dto.rules),status:dto.status,sortOrder:dto.sortOrder,scheduledFor:dto.scheduledFor?new Date(dto.scheduledFor):null,publishedAt:dto.status==='PUBLISHED'?new Date():undefined,archivedAt:dto.status==='ARCHIVED'?new Date():null,items:{create:dto.items}};}
 private targets(items:{mediaTitleId?:string;channelId?:string}[]){if(items.some(v=>Number(!!v.mediaTitleId)+Number(!!v.channelId)!==1))throw new BadRequestException('EXACTLY_ONE_CONTENT_TARGET_REQUIRED');}
 private schedule(status:PublicationStatus,date?:string){if(status==='SCHEDULED'&&(!date||new Date(date)<=new Date()))throw new BadRequestException('FUTURE_SCHEDULE_REQUIRED');}
 private validateTranslations(value:Record<string,string>){if(!value.fr||!value.en||!value.ar)throw new BadRequestException('FR_EN_AR_TRANSLATIONS_REQUIRED');}
 private json(value?:Record<string,unknown>|Record<string,string>){return value as Prisma.InputJsonValue|undefined;}
 private audit(actorId:string,entityType:string,entityId:string,action:string,before:unknown,after:unknown){return this.prisma.contentAuditEvent.create({data:{actorId,entityType,entityId,action,before:before?JSON.parse(JSON.stringify(before)) as Prisma.InputJsonValue:Prisma.JsonNull,after:after?JSON.parse(JSON.stringify(after)) as Prisma.InputJsonValue:Prisma.JsonNull}});}}
