CREATE TYPE "OrderStatus" AS ENUM ('PENDING','PAYMENT_PENDING','PAID','FAILED','CANCELLED','REFUNDED','DISPUTED');
CREATE TYPE "SubscriptionStatus" AS ENUM ('PENDING','ACTIVE','PAST_DUE','SUSPENDED','EXPIRED','CANCELLED');
CREATE TYPE "PaymentEventType" AS ENUM ('SUCCEEDED','FAILED','DELAYED','REFUNDED','DISPUTED');
CREATE TYPE "EntitlementScope" AS ENUM ('LIVE','VOD','SERIES');
CREATE TABLE "Cart" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"countryCode" TEXT NOT NULL,"currency" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CartItem" ("id" TEXT PRIMARY KEY,"cartId" TEXT NOT NULL,"packageId" TEXT NOT NULL,"period" "BillingPeriod" NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Order" ("id" TEXT PRIMARY KEY,"number" TEXT NOT NULL,"userId" TEXT NOT NULL,"packageId" TEXT NOT NULL,"period" "BillingPeriod" NOT NULL,"status" "OrderStatus" NOT NULL DEFAULT 'PENDING',"productSnapshot" JSONB NOT NULL,"contentSnapshot" JSONB NOT NULL,"countryCode" TEXT NOT NULL,"currency" TEXT NOT NULL,"subtotalMinor" INTEGER NOT NULL,"taxMinor" INTEGER NOT NULL,"totalMinor" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"paidAt" TIMESTAMP(3));
CREATE TABLE "PaymentEvent" ("id" TEXT PRIMARY KEY,"externalId" TEXT NOT NULL,"orderId" TEXT NOT NULL,"type" "PaymentEventType" NOT NULL,"payload" JSONB NOT NULL,"processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Subscription" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"orderId" TEXT NOT NULL,"packageId" TEXT NOT NULL,"status" "SubscriptionStatus" NOT NULL DEFAULT 'PENDING',"startsAt" TIMESTAMP(3),"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Entitlement" ("id" TEXT PRIMARY KEY,"subscriptionId" TEXT NOT NULL,"scope" "EntitlementScope" NOT NULL,"channelId" TEXT,"active" BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE "CustomerDevice" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"deviceId" TEXT NOT NULL,"label" TEXT,"lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "CartItem_cartId_packageId_period_key" ON "CartItem"("cartId","packageId","period"); CREATE INDEX "Cart_userId_active_idx" ON "Cart"("userId","active");
CREATE UNIQUE INDEX "Order_number_key" ON "Order"("number"); CREATE INDEX "Order_userId_createdAt_idx" ON "Order"("userId","createdAt");
CREATE UNIQUE INDEX "PaymentEvent_externalId_key" ON "PaymentEvent"("externalId"); CREATE INDEX "PaymentEvent_orderId_processedAt_idx" ON "PaymentEvent"("orderId","processedAt");
CREATE UNIQUE INDEX "Subscription_orderId_key" ON "Subscription"("orderId"); CREATE INDEX "Subscription_userId_status_expiresAt_idx" ON "Subscription"("userId","status","expiresAt");
CREATE UNIQUE INDEX "Entitlement_subscriptionId_scope_channelId_key" ON "Entitlement"("subscriptionId","scope","channelId"); CREATE INDEX "Entitlement_scope_channelId_active_idx" ON "Entitlement"("scope","channelId","active");
CREATE UNIQUE INDEX "CustomerDevice_userId_deviceId_key" ON "CustomerDevice"("userId","deviceId");
ALTER TABLE "Cart" ADD CONSTRAINT "Cart_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_cartId_fkey" FOREIGN KEY ("cartId") REFERENCES "Cart"("id") ON DELETE CASCADE; ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_packageId_fkey" FOREIGN KEY ("packageId") REFERENCES "Package"("id");
ALTER TABLE "Order" ADD CONSTRAINT "Order_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id"); ALTER TABLE "Order" ADD CONSTRAINT "Order_packageId_fkey" FOREIGN KEY ("packageId") REFERENCES "Package"("id");
ALTER TABLE "PaymentEvent" ADD CONSTRAINT "PaymentEvent_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id");
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id"); ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id"); ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_packageId_fkey" FOREIGN KEY ("packageId") REFERENCES "Package"("id");
ALTER TABLE "Entitlement" ADD CONSTRAINT "Entitlement_subscriptionId_fkey" FOREIGN KEY ("subscriptionId") REFERENCES "Subscription"("id") ON DELETE CASCADE;
ALTER TABLE "CustomerDevice" ADD CONSTRAINT "CustomerDevice_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
